                       zpCurntTeamLoopVal = $000091; !^ 00 Home 02 Away ^!
                       Selected_Goalie = $0017AA
                       Selected_Goalie_Awy = $0017AC
                       Def_Ctrl = $001C94; !^ Def Control On or Off 1c94+y = Home 1c94 = Away ^!
                       Def_Ctrl_Awy = $001C96; !^ Def Control On or Off 1c96 = Away ^!
                       PenaltiesOnOff = $7E34C4
                       CurntTeamLoopVal = $9E0091; !^ 00 Home 02 Away ^!
                       JoyPad = $9E0776
                       PauseScreenActive = $9E15DA
                       period = $9E1630
                       clock_remaining_time = $9E1632
                       BreakAwayTrigger_flg = $9E1638
                       GmStat_PenaltyCnt = $9E174A; !^ # of Penalties ^!
                       GmStat_PenaltyMins = $9E174E; !^ Penalty Mins ^!
                       GmStat_AtckZneTme = $9E1752; !^ Attack Zone Time ^!
                       GmStat_PPMins = $9E1756; !^ PP Minutes ^!
                       GmStat_SHGoals = $9E1762; !^ Short Handed Goals ^!
                       GmStat_Shots = $9E177A; !^ Shots On Net ^!
                       GmStat_ShotsAwy = $9E177C; !^ Shots ON Net Away ^!
                       Score_HmAw = $9E178E; !^ 178E Home 1790 Away Score ^!
                       GmStat_FceOffWins = $9E1792; !^ FaceOff Wins ^!
                       PlyrsOnIceCountHm = $9E17A6; !^ Player Count ON Ice ^!
                       PlyrsOnIceCountAwy = $9E17A8; !^ Player Count On Ice ^!
                       GoalieInNetHmAw = $9E17AA
                       GmStat_PassesMade = $9E17BA; !^ Passes Made ^!
                       GmStat_PasCmplt = $9E17BE; !^ Passes Complete ^!
                       GmStat_BrkAwayAttmpts = $9E17C2; !^ Breakaway Attempts ^!
                       GmStat_BrkAwayMade = $9E17C6; !^ Breakaways Made ^!
                       GmStat_PnltyShotMade = $9E17CE; !^ Penalty Shots Made ^!
                       GmStat_OneTmrAtmpt = $9E17D6; !^ One Timer Attempts ^!
                       GmStat_OneTimrMade = $9E17DA; !^ On Timers Made ^!
                       JyPadHmAwy = $9E1C84; !^ 01 Home 02 Away ^!
                       OneTimerFlg = $9E1E89; !^ OneTimer ^!
                       BreakAwayActive_flg = $9E1E8B; !^ Break Away Flag 01 ^!
                       IsPenaltyShot = $9E1E9B
                       EdLnSelLineIndx = $9F0D43; !^ Edit Lines Selected Line Index 1-7 ^!
                       EdLnCurPositionIndex = $9F1D8B; !^ 0-4 0=RW 1=C 2=LW 3=RD 4=LD; PK 0=C 1=LW 2=RD 3=LD ^!
                       EdLnSelPlyIndx = $9F1D8F; !^ Edit Lines Selected Player Index ^!
                       EdLnAvlPlayersCount = $9F1D9F; !^ 4 if pk; 5 if Line 1-3 or PP ^!
                       CODE_00801A = $00801A
                       CODE_008147 = $008147
                       CODE_0084E5 = $0084E5
                       PTR16_00FFFF = $00FFFF
                       LOOSE_OP_808185 = $808185
                       LOOSE_OP_808468 = $808468
                       LOOSE_OP_8084FF = $8084FF
                       LOOSE_OP_80BCD9 = $80BCD9
                       LOOSE_OP_80C0F4 = $80C0F4
                       LOOSE_OP_9C9A57 = $9C9A57
                       LOOSE_OP_9C9A59 = $9C9A59
                       CODE_9FD407 = $9FD407
                       CODE_80A17D = $80A17D
                       Set_Default_Goalie = $9FC6B2
                       CODE_9EBA67 = $9EBA67
                       CODE_9EC06D = $9EC06D
                       jmpToGoalLogic = $9E920F
                       PStructRNG = $9E1A12; !^ Random Number Generator for Attributes ^!
                       CODE_9B8D72 = $9B8D72
                       CODE_9B8D7C = $9B8D7C                       