name: Create Release Copilot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: "Set current date as env variable"
      run: |
          echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      id: version  # this is used on variable path

    - name: Restore dependencies
      run: dotnet restore ./GUI

    - name: Build
      run: |
            cd GUI
            dotnet publish /p:PublishProfile=Winx86Publish.pubxml
            dotnet publish /p:PublishProfile=Osx64Publish.pubxml

    - name: Zip artifacts
      run: |
        sudo apt-get install zip
        zip -r Snes94Hacks-${{ steps.version.outputs.builddate }}-win-x86.zip ${{ github.workspace }}/GUI/94Hacks/publish/WinX86
        zip -r Snes94Hacks-${{ steps.version.outputs.builddate }}-osx64.zip ${{ github.workspace }}/GUI/94Hacks/publish/OSX64

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.builddate }}
        release_name: NHL94 SNES Vault ${{ steps.version.outputs.builddate }}

    - name: Generate release notes
      id: release_notes
      uses: decathlon/release-notes-generator-action@v3.1.6
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update release
      uses: ncipollo/release-action@v1
      with:
        body: ${{ steps.release_notes.outputs.notes }}
        draft: false
        prerelease: false
        tag: ${{ steps.version.outputs.builddate }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      id: upload-release-asset1 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/GUI/94Hacks/publish/WinX86/Snes94Hacks-${{ steps.version.outputs.builddate }}-win-x86.zip
        asset_name: Snes94Hacks-${{ steps.version.outputs.builddate }}-win-x86.zip
        asset_content_type: application/zip

    - name: Upload Release Asset
      id: upload-release-asset2 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/GUI/94Hacks/publish/WinX86/Snes94Hacks-${{ steps.version.outputs.builddate }}-osx64.zip
        asset_name: Snes94Hacks-${{ steps.version.outputs.builddate }}-osx64.zip
        asset_content_type: application/zip
