# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
            cd GUI
            dotnet restore
    - name: Build
      run: |
            cd GUI
            dotnet publish /p:PublishProfile=Winx86Publish.pubxml
    - name: Publish File
      uses: actions/upload-artifact@v4
      with:
          name: Snes94Hacks-$(date +'%Y%m%d')-win-x86
          path: ${{ github.workspace }}/GUI/94Hacks/publish/**/*
