name: Create Relase with Artifacts

on: workflow_dispatch

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
      - name: "Set current date as env variable"
        run: |
            echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        id: version  # this is used on variable path
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: |
              cd GUI
              dotnet restore
      - name: Build
        run: |
              cd GUI
              dotnet publish /p:PublishProfile=Winx86Publish.pubxml
              dotnet publish /p:PublishProfile=Osx64Publish.pubxml      
      
      - name: Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          release_version: ${{ steps.version.outputs.builddate }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_changelog: false

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: NHL94'' SNES Vault ${{ steps.version.outputs.builddate }}
          tag_name: ${{ github.ref }}
          body: ${{ steps.changelog-ci.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ github.token }}            
      
      - name: upload darwin artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/GUI/94Hacks/publish/OSX64/**/*
          asset_name: Snes94Hacks-${{ steps.version.outputs.builddate }}-osx64
          asset_content_type: application/gzip
      
      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/GUI/94Hacks/publish/WinX86/**/*
          asset_name: Snes94Hacks-${{ steps.version.outputs.builddate }}-win-x86
          asset_content_type: application/zip
